module.exports = {
  napster: [
    'https://app.napster.com/artist/yokem/album/boombeats',
    // 'https://app.napster.com/artist/mahone/album/stone-distraction',
    // 'https://app.napster.com/artist/hazel/album/electric-nature',
    // 'https://app.napster.com/artist/dj-reid/album/satisfaction-spell',
    'https://app.napster.com/artist/xondes/album/the-last-heat',
    // 'https://app.napster.com/artist/dj-otl/album/about-other-people',
    'https://app.napster.com/artist/lenitap/album/above-everybody-wind',
    // 'https://app.napster.com/artist/honey/album/just-another-emotion',
    // 'https://app.napster.com/artist/dhn/album/blue-gun',
    // 'https://app.napster.com/artist/hanke/album/new-york-story',
    // 'https://app.napster.com/artist/hanke/album/100-revenge',
    // 'https://app.napster.com/artist/lapilluledors/album/red-beast',
  ],
  amazon: [
    'https://music.amazon.fr/albums/B07CZDXC9B',
    'https://music.amazon.fr/albums/B07G5PPYSY',
    'https://music.amazon.fr/albums/B07MTV7JYS',
    'https://music.amazon.fr/albums/B07PGN58LX',
    'https://music.amazon.fr/albums/B07QCBN3Z4',
    'https://music.amazon.fr/albums/B07RGRZL9F',
    'https://music.amazon.fr/albums/B07RNYTBXG',
    'https://music.amazon.fr/albums/B07TC99Y6V',
    'https://music.amazon.fr/albums/B07V4BZFM2',
    // 'https://music.amazon.fr/albums/B07G9RM2MG',
    // 'https://music.amazon.fr/albums/B07D3NQ235',
    // 'https://music.amazon.fr/albums/B07D3PGSR4',
  ],
  tidal: [
    // 'https://listen.tidal.com/album/93312939',
    'https://listen.tidal.com/album/93087422',
    'https://listen.tidal.com/album/88716570',
    'https://listen.tidal.com/album/101927847',
    'https://listen.tidal.com/album/102564740',
    'https://listen.tidal.com/album/102503463',
    'https://listen.tidal.com/album/105237098',
    'https://listen.tidal.com/album/108790098',
    'https://listen.tidal.com/album/108980716',
    'https://listen.tidal.com/album/111577934',
    'https://listen.tidal.com/album/112969038',
  ],
  spotify: [
    'https://open.spotify.com/album/3FJdPTLyJVPYMqQQUyb6lr',
    'https://open.spotify.com/album/2jmPHLM2be2g19841vHjWE',
    'https://open.spotify.com/album/5CPIRky6BGgl3CCdzMYAXZ',
    'https://open.spotify.com/album/0Tt1ldQ8b4zn5LRcM706ll',
    'https://open.spotify.com/album/2kFEMTIWWw0jXD57Ewr7go',
    'https://open.spotify.com/album/4BR7o0DwEPj1wF1nfcypiY',
    'https://open.spotify.com/album/6045wkKBhEx1DBoqn3aXSe',
    'https://open.spotify.com/album/7Jh67aHTA9ly7R1OTbzqGF',
    'https://open.spotify.com/album/6U2LK36oc2VweDgRi0u1A7',
    // 'https://open.spotify.com/episode/5CTWjaln8LbP3JMnDfL2SR',
    // 'https://open.spotify.com/episode/4LNlZZiOy32VQvTGXJ9BR9',
    // 'https://open.spotify.com/episode/0zDeN4F8lTTrieI3IvsCiI',
    // 'https://open.spotify.com/episode/07AeZf0ExTxB864NZIOGRP',
    // 'https://open.spotify.com/episode/77PytpYZNCs6d8uyzwYn1p',
    // 'https://open.spotify.com/episode/5get1YOTsPf6RAPIySupcV',
    // 'https://open.spotify.com/episode/5QrKbluyFZsg6jJ26ye7f6',
    // 'https://open.spotify.com/episode/4AFzaLO87GuTdtSuIk82r2',
    // 'https://open.spotify.com/episode/5YwlHKInZK9O6So8trYhBm',
    // 'https://open.spotify.com/album/5509gS9cZUrbTFege0fpTk',
  ]
}